### PR TITLE
Text Channel

### PR DESCRIPTION
**Pull request by BryceeL**
Turn the channel into a react component and added CSS for it

### CODE REVIEW

**Review by jcb-2004 — COMMENTED** [review]
I found that the changes were mostly copying code to make TextChannel templates. I tested the site and it works with these changes. I admit that I don't really have much expertise in this area, but it looks fine by me.

**Comment by BradJKim** [comment]
Looks pretty good, would you might sending a screenshot of what that look like as well? I forgot to mention but I would love to have a reference so that I can compare

**Comment by BryceeL** [comment]
Here is a screenshot of the website
Screenshot 2024-03-20 192504

**Review by BradJKim — APPROVED** [review]
Looks good to me, good job with componentizing the text channel, you can argue that you may not need it exactly since it isn't used much, but it makes the code look a lot cleaner so I think it'll be good. Also acts as good experience with componentization.

**Pull request merged**
